### ISSUE TITLE
Search Example

### ISSUE THREAD

**Issue by taat** [andsalves/doctrine-elastic#19]
Could you provide example how to get search results?

Usually I'd connect to Elastic search and issue: `q=<my query>`

I tried to do:

```````
$manager->createQuery('my query')->getResult()
```````

but it stops somewhere around `QueryParser::getAST()`

`$this->lexer->lookahead['type']` is `100`

**Comment by taat** [comment]
This worked finally:
        
`````
$manager->createQuery("Select u.customField  from Application\\Entity\\FooType u where u.customNumericField=111")->getResult();
`````

**Comment by andsalves** [comment]
Hi @taat, 
doctrine-elastic works based in Doctrine defaults. However, a few of things are not the same. 

For simple queries as that, you can simply use findBy or findOneBy, as you can see in https://github.com/andsalves/doctrine-elastic#finding-documents (README). In your case:
```````
$results = $manager->getRepository("Application\\Entity\\FooType")->findBy(['customNumericField' => 111]);
```````

For more complex queries, you can use queryBuilder. With that, you can assemble queries with different operators like ">", "<", "LIKE", "!=" and so on. It's also possible to group "AND" and "OR" queries like in SQL. Here is an example of more complex query using queryBuilder:

```````
$queryBuilder = $manager->getRepository(Application\Entity\FooType::class)->createQueryBuilder('f');
$queryBuilder->where("f.customNumericField = 111");
$queryBuilder->andWhere(
    $queryBuilder->expr()->or(
        $queryBuilder->expr()->eq('f.foodField', $queryBuilder->expr()->literal('bacon')),
        $queryBuilder->expr()->like('f.foodField', $queryBuilder->expr()->literal('steak')),
    )
);

$queryBuilder->andWhere(
    $queryBuilder->expr()->between('f.dateField', '2018-05-01', '2022-09-01')
);

$results = $queryBuilder->getResults();
```````

Take note:
- It's not possible to get only some specific fields from any doctrine-elastic query. The results always will be the entire entity with all its fields. So "Select u.customField ..." probably returns the same of "Select u ...". 
- $manager->createQuery('...') creates a default query based in the DQL query you provide. Is not the same as queryBuilder, but you can use this approach as well. You can set a DQL for a queryBuilder as you can also get the DQL query from a current queryBuilder. These features are from Doctrine itself, I only implemented them for doctrine-elastic. Particularly I recommend use only queryBuilder as the example above.   
- You cannot make joins from queryBuilder easily as in Doctrine. I tryed to implement this but if you need this, probably elasticsearch is not the best choice. 

Regards.

**Comment by taat** [comment]
Thanks for the examples. 

Looks like a method which will support Lucene syntax (like `q=speaker:King`) would be helpful, and easy to implement, as this is just passing the query term via curl to ElasticSearch. (Assumming we don't need parsers, syntax validator etc.). This syntax is well documented on ElasticSearch website.

And the next step are hydrators :) Are there any built in?

Is there any particular reason it always returns all the fields? Seems like a waste of resources.

**Comment by andsalves** [comment]
Hey @taat,
The search queries in doctrine-elastic are made with default POST-_search manner because of the complexity in some DQL queries. Adding different ways to assemble search queries will make the code more complex and hard to maintain. Unless the benefits outgrow that. 

As well, I realised that specifc-fields query will bring an extra effort which is unnecessary currently, and the performance gains are negligible or absent. Even in Doctrine I'm not used to use that feature, as it's much better work with Entity objects.
